---
- name: Verify
  hosts: all
  gather_facts: true
  become: true
  vars:
    _package: rabbitmq-server
  tasks:
    - name: Check rabbitmq package availability for Debian derivatives
      ansible.builtin.shell:
        cmd: set -o pipefail && apt-cache search {{ _package }} | awk '{print $1}' | grep "^{{ _package }}$"
        executable: /bin/bash
      when: ansible_os_family | lower == 'debian'
